---
- 
  
  hosts: webservers
  become: yes
  
  tasks:

    - name: update cache
      apt:
        update_cache: true
      become: true

    - name: install pip
      apt:
        name: python3-pip
        state: present
        update_cache: true

    - name: install flask with pip
      pip:
        executable: pip
        name: flask
        state: latest

    - name: install gunicorn
      apt:
        name: gunicorn
        state : present

    - name: install snmpd
      apt:
        name: snmpd
        state: latest

    - name: Configure snmpd
      template:
        src: "./snmpd.conf"
        dest: "/etc/snmp/snmpd.conf"
    
    - name: restart snmpd
      service:
        name: snmpd
        state: restarted

    - name: copy the code
      copy:
        src: application2.py
        dest: ./application2.py
        owner: ubuntu
        mode: '0644'

    - name: Run Flask app
      shell: gunicorn -w 2 -D -b 0.0.0.0:8080 application2:app
      
# haproxy configuration

- hosts: webservers
  gather_facts: yes
- hosts: HAproxy
  become: yes

  tasks:

    - name: update apt cache
      become: true
      apt:
        update_cache: true

    - name: install haproxy
      become: true
      apt:
        name: haproxy
        state: latest

    - name: deploy new haproxy configuration
      template:
        src: /$PWD/haproxy.cfg.j2
        dest: "/etc/haproxy/haproxy.cfg"

    - name: Haproxy restart
      service:
        name: haproxy
        state: restarted
  
    - name: installing Nginx 
      apt:
        name: nginx
        state: latest
       
    - name: Configuring nginx for UDP loadbalancing  
      template:
        src: "./nginx.conf.j2"
        dest: "/etc/nginx/nginx.conf"

    - name: restarting nginx
      service:
         name: nginx
         state: restarted
